<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SalePayments extends Model
{
    use HasFactory;

    protected $table = 'sale_payments';
    protected $fillable = [
        'sale_payment_id',
        'createdDate',
        'modifiedDate',
        'paymentDate',
        'amount',
        'method',
        'isAuthorized',
        'transactionRef',
        'comments',
        'orderId',
        'orderRef',
        'paymentImportedRef',
        'batchReference',
        'reconcileDate',
        'branchId',
        'orderType',
        'customer_first_name',
        'customer_last_name',
        'invoice_number',
        'po_number',
        'company',
        'email',
        "createdBy",
        "processedBy",
        "isApproved",
        "memberId",
        "phone",
        "mobile",
        "fax",
        "deliveryFirstName",
        "deliveryLastName",
        "deliveryCompany",
        "deliveryAddress1",
        "deliveryAddress2",
        "deliveryCity",
        "deliveryState",
        "deliveryPostalCode",
        "deliveryCountry",
        "billingFirstName",
        "billingLastName",
        "billingCompany",
        "billingAddress1",
        "billingAddress2",
        "billingCity",
        "billingPostalCode",
        "billingState",
        "billingCountry",
        "branchEmail",
        "projectName",
        "trackingCode",
        "internalComments",
        "productTotal",
        "freightTotal",
        "freightDescription",
        "surcharge",
        "surchargeDescription",
        "discountTotal",
        "discountDescription",
        "total",
        "currencyCode",
        "currencyRate",
        "currencySymbol",
        "taxStatus",
        "taxRate",
        "source",
        "customFields",
        "isVoid",
        "memberEmail",
        "memberCostCenter",
        "memberAlternativeTaxRate",
        "costCenter",
        "alternativeTaxRate",
        "estimatedDeliveryDate",
        "salesPersonId",
        "salesPersonEmail",
        "paymentTerms",
        "voucherCode",
        "deliveryInstructions",
        "cancellationDate",
        "modifiedCOGSDate",
        "status",
        "stage",
        "invoiceDate",
        "dispatchedDate",
        "logisticsCarrier",
        "logisticsStatus",
        "ediStatus",
        "distributionBranchId",
        "departmentNumber",
        "storeLocationNumber",
        "distributionCenter",
        'order_created_date',
    ];

}
